### ISSUE TITLE
Can't acess settings

### ISSUE THREAD

**Issue by Jaliborc** [tullamods/Combuctor#118]
@Tuller, something is wrong with this repo since the last change, I can't access the settings like the others ones.

Also, I can't add actions on any repo. Want to add a new one I made that automatically tags version numbers whenever the .toc changes: https://github.com/Jaliborc/PetTracker/actions. Will make commit history easier to search trough.

**Comment by Jaliborc** [comment]
Oh, can't make assignments or put labels on the issues either xD

**Comment by Jaliborc** [comment]
Not even close issues! xD

**Comment by Tuller** [comment]
Permissions should be fixed. Github Actions isn't actually a released thing yet so that's why its not on tullamods. I did, however, turn on travisci for all of the repos.

**Comment by Jaliborc** [comment]
Its working now
