### ISSUE TITLE
Twitch App removes Combuctor, Bag Brother, and Combuctor Config

### ISSUE THREAD

**Issue by Dadrage** [tullamods/Combuctor#136]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.2
 - Server patch: 1.13.3 (Classic)
 **Have you read the changelog? (please don't waste our time)**
 Mark if read. yes

**Describe the bug**
I use the Twitch desktop app to keep all my addons up to date. The Twitch app removes Combuctor when I refresh/update all.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Twitch desktop app
2. Click on Mods
3. Click on World of Warcraft
4. Click Refresh
or
4. Click update all
5. Combuctor, Bagbrother, and Combuctor Config are now missing from 
\World of Warcraft\_classic_\Interface\AddOns\

**Comment by Jaliborc** [comment]
I have no control over the twitch app. Please contact twitch. Sorry.

**Comment by Dadrage** [comment]
Every other add-on i've ever used,  including Bagnon, does just fine in the twitch app and does not get removed. Could it be that the Twitch app thinks Combuctor is a add-on for retail/live and thus removes it out of the Classic add-on folder?

**Comment by Jaliborc** [comment]
¯\_(ツ)_/¯ talk to twitch

**Comment by Dadrage** [comment]
There's no label or tag in Combuctor or possibly when you submit it to Curseforge that labels it a Live/Retail add-on. I really think that is the issue.

**Comment by Dadrage** [comment]
![Capture](https://user-images.githubusercontent.com/61536789/75484249-3e48a400-595d-11ea-8418-01d2685e1924.PNG)

**Comment by Jaliborc** [comment]
![1](https://user-images.githubusercontent.com/442637/75484334-dfa91780-59a8-11ea-9921-2a328ae390bd.PNG)
Talk. To. Twitch.

**Comment by Dadrage** [comment]
Nah. If you want to fix your add on with Curse / Twitch that's on you.
