### ISSUE TITLE
"Bag Break" does nothing

### ISSUE THREAD

**Issue by AySz88** [tullamods/Combuctor#142]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 8.3.2
 - Server patch: 8.3.0.34601

 **Have you read the changelog?** Yes

**Describe the bug**
"Bag Break" option does not do anything.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Game Menu > Interface > AddOns > Frame Settings
2. For the "Inventory" Frame, check the box for "Bag Break", under Appearance
3. Click OK.
4. Press the keybind for bags (B) to open inventory.

**Expected behaviour**
When the toggle is checked, items are laid out on new lines whenever a new bag is reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/3681319/84006566-f3b3cc00-a93c-11ea-9a94-ea88d509e94c.png)

**Error Logs**
No errors in session

**Additional context**
The "Bag Break" toggle does work with Bagnon, but not Combuctor. I have both installed to compare them, but only have Combuctor enabled.
Similarly: It appears that the "Rulesets on Left" toggle does not do anything. The "Bag Break" and "Rulesets on Left" toggles don't work on the Bank frame either.

**Comment by Ethan-BB** [comment]
I can confirm, this behaviour is still unchanged as of 16. Oct 2020.
Would be lovely to see this fixed, as it's only think keeping me with Bagnon.
