### ISSUE TITLE
lua error when using a keybind

### ISSUE THREAD

**Issue by waytoomuchgaming** [tullamods/Combuctor#151]
**Running Software (issues missing this information will be deleted):**
 - Addon version: 9.0.2
 - Server patch: 1.13.6

 **Have you read the changelog? (please don't waste our time)**
yes

**Describe the bug**
1x [string "COMBUCTOR_TOGGLE"]:1: attempt to call method 'ToggleFrame' (a nil value)
[string "COMBUCTOR_TOGGLE"]:1: in function <[string "COMBUCTOR_TOGGLE"]:1>

Locals:
keystate = "down"
pressure = 1
angle = -1
precision = 0
(*temporary) = nil
(*temporary) = <table> {
 IsKeyring = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:381
 FrameTemplate = true
 IsRetail = false
 GetOwnerID = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:271
 Frames = <table> {
 }
 InBank = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:358
 BottomTab = <table> {
 }
 ItemGroup = <table> {
 }
 GeneralOptions = <unnamed> {
 }
 RestoreItemData = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:305
 Frame = <table> {
 }
 SideTab = <table> {
 }
 RuleFilter = <table> {
 }
 Bag = <table> {
 }
 IsBank = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:385
 RegisterMessage = <function> defined @BCT\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IsBackpack = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:373
 IsBagCached = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:292
 SideFilter = <table> {
 }
 Base = <table> {
 }
 UnregisterSignal = <function> defined @Combuctor\common\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 GetOwnerAddress = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:276
 RegisterEvent = <function> defined @BCT\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 QualityButton = <table> {
 }
 OnEnable = <function> defined @Combuctor\common\Wildpants.lua:98
 Name = "Combuctor"
 IterateOwners = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:115
 InGuild = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:366
 SendSignal = <function> defined @Combuctor\common\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 UnregisterAllEvents = <function> defined @BCT\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RestoreLinkData = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:329
 GetModule = <function> defined @Combuctor\addons\main\legacy.lua:11
 Item = <table> {
 }
 RuleOptions = <unnamed> {
 }
 ColorOptions = <unnamed> {
 }
 Slash = "cbt"
 DisplayOptions = <unnamed> {
 }
 OwnerSelector = <table> {
 }
 OptionsGroup = <table> {
 }
 Commands = <table> {
 }
 profile = <table> {
 }
 SortButton = <table> {
 }
 sets = <table> {
 }
 InventoryFrame = <table> {
 }
 Sets = <table> {
 }
 BottomFilter = <table> {
 }
 BagGroup = <table> {
 }
 QualityFilter = <table> {
 }
 Events = <table> {
 }
 AutoDisplay = <table> {
 }
 TooltipCounts = <table> {
 }
 BagToggle = <table> {
 }
 PickupItem = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:251
 Tag = "COMBUCTOR_"
 NewModule = <function> defined @Combuctor\common\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 IsBackpackBag = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:377
 GetOwnerInfo = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:75
 UnregisterMessage = <function> defined @BCT\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 DropButton = <table> {
 }
 IsOwnerCached = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:288
 BankFrame = <table> {
 }
 InVault = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:362
 GetItemID = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:230
 IsReagents = <function> defined @Combuctor\common\libs\LibItemCache-2.0\LibItemCache-2.0.lua:393
 IsBankBag = <function

**To Reproduce**
https://github.com/tullamods/Combuctor/issues/141

**Comment by hoshbad** [comment]
Is addressed by Pull Request https://github.com/tullamods/Combuctor/pull/162

**Comment by Jaliborc** [comment]
Is fixed in 9.1
