### ISSUE TITLE
Most items not loading pictures

### ISSUE THREAD

**Issue by RoadKill2121** [tullamods/Combuctor#175]
Is anyone having problems with items not loading since the new patch? I have tried removing and reinstallation of the addon. Refreshing the UI, Nothing seems to change this. It was working yesterday.

![image](https://user-images.githubusercontent.com/102188558/159575856-9fd0502c-c661-4d7c-9346-b2ce3760e005.png)
![image](https://user-images.githubusercontent.com/102188558/159575833-abd0248a-4653-4bc2-9505-f3b595238fc3.png)

 

**Screenshots**
![image](https://user-images.githubusercontent.com/102188558/159575683-3bd7efab-97af-4443-ab02-fe324e891576.png)

**Comment by WMoerke** [comment]
I discovered a temporary fix that will work until there is an update.

Go to your addons folder and find this file -  AddOns\Combuctor\common\libs\LibItemSearch-1.2\LibItemSearch-1.2.lua

Open it in an editor and in the file on line 250 you'll find:
`if C_AzeriteItem then`

Change it to:
`if C_AzeriteItem and C_CurrencyInfo.GetAzeriteCurrencyID then`

That should fix the problem.

**Comment by RoadKill2121** [comment]
This worked, Thank you very much sir. 
![image](https://user-images.githubusercontent.com/102188558/159596243-64dc7554-ae09-4709-a3ec-a4ce762c5e5b.png)
