### ISSUE TITLE
WOTLK Error

### ISSUE THREAD

**Issue by SegoItCh** [tullamods/Combuctor#183]
57x FrameXML\ContainerFrame_Shared.lua:1298: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: GameTooltip:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML\ContainerFrame_Shared.lua"]:1298: in function `ContainerFrameItemButton_CalculateItemTooltipAnchors'
[string "@FrameXML\ContainerFrame_Shared.lua"]:1344: in function <FrameXML\ContainerFrame_Shared.lua:1304>
[string "=[C]"]: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:369: in function `ShowTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:340: in function `UpdateTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:180: in function <...faceBagnon\common\Wildpants\classes\item.lua:179>

Locals:
(*temporary) = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 ttNumLines = 0
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:390
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined =[C]:-1
 _owner = QuestieFrame197 {
 }
 RightEdge = <unnamed> {
 }
 questOrder = <table> {
 }
 ttSetBackdropBorderColorLocked = true
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:282
 SetLootItem = <function> defined =[C]:-1
 ttDefaultAnchored = false
 ttGradient = <unnamed> {
 }
 numMoneyFrames = 6
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:214
 TopRightCorner = <unnamed> {
 }
 ttLastUpdate = 0
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:188
 updateTooltip = 0.181000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @TipTac\ttCore.lua:1537
 LeftEdge = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 TopLeftCorner = <unnamed> {
 }
 miniMapIcon = false
 ttAnchorType = "mouse"
 ttDisplayingUnit = false
 SetCraftItem = <function> defined =[C]:-1
 ttDisplayingAura = false
 0 = <userdata>
 ApplyBackdrop = <function> defined @TipTac\ttCore.lua:1521
 SetBackdrop = <function> defined @TipTac\ttCore.lua:1529
 SetTradeSkillItem = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 ttBackdropBorderColorApplied = false
 SetQuestItem = <function> defined =[C]:-1
 FadeOut = <function> defined @TipTac\ttCore.lua:1334
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:266
 BottomOverlay = <unnamed> {
 }
 ttUnit = <table> {
 }
 NineSlice = <unnamed> {
 }
 TooltipBackdropOnLoad = <function> defined @SharedXML\SharedTooltipTemplates.lua:172
 SetInboxItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 NWBSeparator = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @TipTac\ttCore.lua:1545
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:182
 SetTradeTargetItem = <function> defined =[C]:-1
 manualOrder = <table> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 BottomEdge = <unnamed> {
 }
 SetSendMailItem = <function> defined =[C]:-1
 ttSetBackdropLocked = true
 canAddRestStateLine = 1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:278
 ttBackdropColorApplied = false
 __tamedCounts = true
 SetQuestLogItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 comparing = false
 ttSetBackdropColorLocked = true
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:246
 ttAnchorPoint = "TOPRIGHT"
 npcOrder = <table> {
 }
 backdropInfo = <table> {
 }
}
(*temporary) = "BOTTOMRIGHT"
(*temporary) = ContainerFrame1Item5 {
 0 = <userdata>
 OnEnter = <function> defined @Bagnon\common\Wildpants\classes\item.lua:179
 __super = <table> {
 }
 GetSlotType = <function> defined @Bagnon\common\Wildpants\classes\item.lua:469
 IconOverlay = <unnamed> {
 }
 SlotTypes = <table> {
 }
 UpdateCooldown = <function> defined @Bagnon\common\Wildpants\classes\item.lua:290
 Bind = <function> defined @Bagnon\common\Wildpants\classes\item.lua:101
 IconBorder = <unnamed> {
 }
 flashAnim = <unnamed> {
 }
 SetLocked = <f

**Comment by Jaliborc** [comment]
TipTac problem I heard
