### ISSUE TITLE
enhancement: make the profile global by default

### ISSUE THREAD

**Issue by essmene** [tullamods/Combuctor#38]
Hi,

I started over with combuctor and I am somewhat annoyed, that I have to visit each single character and open the combuctor config - enable all/all ,... and other settings by hand, where I would like to have the same setting on every single character (and for the time being i cannot imagine, why somebody would like to have a different setup for every character).

Would it be possible to set the default profile to default instead of server/character?

**Comment by Jaliborc** [comment]
Now you can toggle between a global profile or character specific settings
