### ISSUE TITLE
Bag slots scrambling placement

### ISSUE THREAD

**Issue by Thrumbar** [tullamods/Combuctor#39]
Items in bags scramble up messing up order I placed them in requiring RL to fix .  Others are leaving comments on Curse about this as in the following

"I'm also getting the same bug with bags re-ordering themselves and as a post below says, it seems to be the last three bags.

They seem to re-order themselves when you take a portal / enter/leave a dungeon.

If after a portal you do a /reload then it seems to order properly again."

**Comment by phant** [comment]
i have placement bug too
4 x 30 slot bags
video https://youtu.be/2ww2EAqWTsE

**Comment by Jaliborc** [comment]
Completely new codebase makes this a deprecated issue.
