### ISSUE TITLE
Regent Bank Issue

### ISSUE THREAD

**Issue by ytzyt** [tullamods/Combuctor#72]
When the regent bank has no empty slot, items will be deposited into other bags regardless of if the regent bank has same stackable item that is not at maximum stack.

eg.
1) regent bank has 0 empty slot, but item A's stack is only at 1/200
2) try to right click on item A with 199/200 stack in backpack
3) item A will go into other bags instead of making a 200/200 stack

if there is at least 1 empty slot available in regent bank, item A will stack to 200/200 in regent bank.

**Comment by Jaliborc** [comment]
Duplicate
