### ISSUE TITLE
Reverse Cleanup Bags is always force enabled

### ISSUE THREAD

**Issue by Spectrose** [tullamods/Combuctor#73]
The interface option, under Controls, Reverse Clean Up Bags always turns back on after turning it off.  This option, when checked, causes the Clean Up Bags button to move items to the rightmost bags.  This causes the clean up option to sort the singular Combuctor bag to the top, and gives no option to sort to the bottom.  Can this get fixed?

**Comment by Jaliborc** [comment]
This will most likely change when Combuctor moves to the new arquitecture
