### ISSUE TITLE
Compatibility with 7.0.3

### ISSUE THREAD

**Issue by huhlig** [tullamods/Combuctor#77]
New Expansion patch breaks Combuctor as expected. 

Currently opening the inventory shows 0 items and 0 item slots.

**Comment by Snoopza** [comment]
@Tuller @Jaliborc .  Would it be possible to get an ETA on a possible fix for Combuctor please gents?

**Comment by herrevilkitten** [comment]
I've got a mostly fixed version.  There's still some weirdness (Devices and Explosives may have gone away).  I'll make a fork and do a pull request later today.

**Comment by Snoopza** [comment]
Will it be available through Curse, or would we need to use SVN to download it?

**Comment by herrevilkitten** [comment]
Anyone should be able to download a ZIP of the repository from github.  I can provide a Curse package as well, but I'll likely call it something like "Combuctor_Unofficial_Legion_Fixes" to prevent confusion with the real package.

**Comment by herrevilkitten** [comment]
https://github.com/herrevilkitten/Combuctor

https://github.com/herrevilkitten/Combuctor_Sets

**Comment by huhlig** [comment]
@herrevilkitten I am getting the following with your version.

Message: Interface\AddOns\Combuctor\components\frame.lua:88: attempt to call method 'New' (a nil value)
Time: 07/21/16 17:01:49
Count: 1
Stack: Interface\AddOns\Combuctor\main.lua:38: in function <Interface\AddOns\Combuctor\main.lua:24>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...s\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: ?
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:993: in function <Interface\FrameXML\UIParent.lua:891>

Locals: self = <table> {
 FrameEvents = <unnamed> {
 }
 BottomFilter = <unnamed> {
 }
 EnableModule = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 ItemSlot = <unnamed> {
 }
 IterateEmbeds = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 UpdateFrames = <function> defined @Interface\AddOns\Combuctor\main.lua:259
 ToggleSetting = <function> defined @Interface\AddOns\Combuctor\main.lua:78
 BottomTab = <unnamed> {
 }
 Printf = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 Show = <function> defined @Interface\AddOns\Combuctor\main.lua:226
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Frame = <unnamed> {
 }
 DisableModule = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 BagEvents = <table> {
 }
 GetBaseProfile = <function> defined @Interface\AddOns\Combuctor\main.lua:138
 RegisterMessage = <function> defined @Interface\AddOns\LibAboutPanel\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 GetArgs = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 UpdateSettings = <function> defined @Interface\AddOns\Combuctor\main.lua:66
 Toggle = <function> defined @Interface\AddOns\Combuctor\main.lua:248
 SideFilter = <unnamed> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\LibAboutPanel\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 sets = <table> {
 }
 IterateModules = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 HookBagEvents = <function> defined @Interface\AddOns\Combuctor\main.lua:159
 ItemFrame = <unnamed> {
 }
 Enable = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:325
 RegisterChatCommand = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 GetModule = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 defaultModuleLibraries = <table> {
 }
 Hide = <function> defined @Interface\AddOns\Combuctor\main.lua:237
 UnregisterChatCommand = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 GetName = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 profile = <table> {
 }
 name = "Combuctor"
 InitProfile = <function> defined @Interface\AddOns\Combuctor\main.lua:126
 orderedModules = <table> {
 }
 Disable = <function> defined @Interface\AddOns\AckisRecipeList\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 NewClass = <function> defined @Interface\AddOns\Combuctor\api\classes.lua:8
 QualityFilter = <unnamed> {
 }
 QualityFilterButton = <unnamed> {
 }
 Print

**Comment by herrevilkitten** [comment]
Unfortunately, I don't actually know much about Warcraft addons :) My initial suspicion is that Combuctor is using the version of AceAddon that is packaged with AckisRecipeList and something weird is going on.  The error you gave is on this line

````
	f.itemFrame = Addon.ItemFrame:New(f, bags)
````

which seems to mean that either there's an error in ItemFrame or it couldn't be loaded.  Do you have any other errors, hopefully in ItemFrame?

**Comment by herrevilkitten** [comment]
Oi. I see the errors now. My diff must have been really messed up.

**Comment by herrevilkitten** [comment]
The zip that github generates doesn't have the dependencies.  Oops.

Try this: https://github.com/herrevilkitten/Combuctor/releases/tag/7.0.0

I'm not getting any lua errors with this.

**Comment by Snoopza** [comment]
@herrevilkitten They should give credit to you for the fixes you have provided in the meantime ;)

**Comment by mjbergeron** [comment]
Thank you, thank you, thank you.

**Comment by zyxakarene** [comment]
I also seem to have an issue with the equipment compare tooltip while using Combuctor (Also any other one-bag addon though):

If I mouse over an item, the tooltop is showing to the top left of the item.
If I hold shift to compare with what I am wearing (Or use Moncai Equip Compare), the thing I am wearing is anchored to the right of the tooltip, effectively blocking the view of my bags.

**Comment by Seerah** [comment]
I am also having this issue with compare tooltips in Combuctor. The itemref tips show only to the right of the GameTooltip and overlap each other at the edge of the screen. I need to move the Combuctor window closer to the middle to be able to see everything.

**Comment by y368413** [comment]
Combuctor\components\item.lua

line354-360
change:
function ItemSlot:AnchorTooltip()
	if self:GetRight() >= (GetScreenWidth() / 2) then
		GameTooltip:SetOwner(self, 'ANCHOR_LEFT')
	else
		GameTooltip:SetOwner(self, 'ANCHOR_RIGHT')
	end
end


to:
function ItemSlot:AnchorTooltip()
  GameTooltip:SetOwner(self, "ANCHOR_CURSOR")
end

can fix the “ itemref tips show only to the right of the GameTooltip” bug.
