### ISSUE TITLE
where this title come from ?

### ISSUE THREAD

**Issue by ggiovannelli** [tullamods/Combuctor#87]
The tab that should be used for TradeGood is labelled in Italian "Incanti!" which is obviusly wrong or at least not correct.

![screenshot_369](https://cloud.githubusercontent.com/assets/17082136/20036048/ce86c1e8-a3fb-11e6-985e-b8f03f499e21.png)

Is possible to fix it ?
Thanks.

**Comment by ggiovannelli** [comment]
![screenshot_373](https://cloud.githubusercontent.com/assets/17082136/20036100/9e99005c-a3fd-11e6-93ac-bc7d158dd2a5.png)

They are not enchants :) they are trade items :))

**Comment by Jaliborc** [comment]
Well, we're using blizzard's translations... cant do anything
