### ISSUE TITLE
Some bugs with 7.1 (Bank view, resizing, move to reagent bank)

### ISSUE THREAD

**Issue by Azami1990** [tullamods/Combuctor#88]
Hey, after updating to 7.1.0 (clear wtf for combuctor) ive got some Errors.
1: When i try to access my Bank from the Bag (visitied Bank befor) i get this error

> 6x ...aceCombuctor\common\components\bagToggle.lua:94: attempt to call method 'ShowFrame' (a nil value)
...aceCombuctor\common\components\bagToggle.lua:94: in function `OpenFrame'
...aceCombuctor\common\components\bagToggle.lua:59: in function <...aceCombuctor\common\components\bagToggle.lua:29>
Locals:
self = <unnamed> {
 0 = <userdata>
 frame = CombuctorFrameinventory {
 }
 Icon = <unnamed> {
 }
 Border = <unnamed> {
 }
}
id = "bank"
addon = nil
frame = CombuctorFramebank {
 0 = <userdata>
 titleText = CombuctorFramebankTitle {
 }
 portrait = CombuctorFramebankPortrait {
 }
 itemFrame = <unnamed> {
 }
 leftBorderBar = CombuctorFramebankLeftBorder {
 }
 player = "Horstlinde"
 bagToggle = <unnamed> {
 }
 bottomFilter = <unnamed> {
 }
 sideFilter = <unnamed> {
 }
 topLeftCorner = CombuctorFramebankTopLeftCorner {
 }
 Bg = CombuctorFramebankBg {
 }
 quality = 0
 frameID = "bank"
 subrule = "all/all"
 moneyFrame = CombuctorFramebankMoneyFrame {
 }
 TopTileStreaks = CombuctorFramebankTopTileStreaks {
 }
 rule = "all"
 qualityFilter = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 sortButton = <unnamed> {
 }
 profile = <table> {
 }
 CloseButton = CombuctorFramebankCloseButton {
 }
 TitleText = CombuctorFramebankTitleText {
 }
 portraitFrame = CombuctorFramebankPortraitFrame {
 }
 searchBox = CombuctorFramebankSearchBox {
 }
 portraitButton = CombuctorFramebankPortraitButton {
 }
 topBorderBar = CombuctorFramebankTopBorder {
 }
 Inset = CombuctorFramebankInset {
 }
}
(*temporary) = nil
(*temporary) = CombuctorFramebank {
 0 = <userdata>
 titleText = CombuctorFramebankTitle {
 }
 portrait = CombuctorFramebankPortrait {
 }
 itemFrame = <unnamed> {
 }
 leftBorderBar = CombuctorFramebankLeftBorder {
 }
 player = "Horstlinde"
 bagToggle = <unnamed> {
 }
 bottomFilter = <unnamed> {
 }
 sideFilter = <unnamed> {
 }
 topLeftCorner = CombuctorFramebankTopLeftCorner {
 }
 Bg = CombuctorFramebankBg {
 }
 quality = 0
 frameID = "bank"
 subrule = "all/all"
 moneyFrame = CombuctorFramebankMoneyFrame {
 }
 TopTileStreaks = CombuctorFramebankTopTileStreaks {
 }
 rule = "all"
 qualityFilter = <unnamed> {
 }
 bagFrame = <unnamed> {
 }
 sortButton = <unnamed> {
 }
 profile = <table> {
 }
 CloseButton = CombuctorFramebankCloseButton {
 }
 TitleText = CombuctorFramebankTitleText {
 }
 portraitFrame = CombuctorFramebankPortraitFrame {
 }
 searchBox = CombuctorFramebankSearchBox {
 }
 portraitButton = CombuctorFramebankPortraitButton {
 }
 topBorderBar = CombuctorFramebankTopBorder {
 }
 Inset = CombuctorFramebankInset {
 }
}
(*temporary) = "attempt to call method 'ShowFrame' (a nil value)"
Addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 Cache = <table> {
 }
 BottomFilter = <unnamed> {
 }
 RegisterDisplayEvents = <function> defined @Combuctor\common\features\autoDisplay.lua:48
 EnableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 StartupProfile = <function> defined @Combuctor\common\core\settings.lua:149
 GetPlayerColor = <function> defined @Combuctor\common\core\players.lua:38
 UpdateFrames = <function> defined @Combuctor\common\core\frames.lua:38
 SetupAutoDisplay = <function> defined @Combuctor\common\features\autoDisplay.lua:8
 BottomTab = <unnamed> {
 }
 Printf = <function> defined @Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 ShowBag = <function> defined @Combuctor\common\core\frames.lua:86
 SetDefaultModulePrototype = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 IsEnabled = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 Frame = <unnamed> {
 }
 DisableModule = <function> defined @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 SetProfile = <function> defined @Combuctor\common\core\settings.lua:155
 Bag = <unnamed> {
 }
 StartupSettings = <function> defined @Combuctor\common\core\settings.lua:91
 RegisterMessage = <function> defined @Masque\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IsBackpack = <function> defined @Combuctor\common\core\bags.lua:11
 UpdateSettings = <function> 

2: The resizing is very wierd. I think the 7.0 Version was much smoother. (https://drive.google.com/open?id=0B2Ksp5IVXgmNOWxfWmdoZTFXQU0)
3: Why is the "Move to regaent bank" gone? I miss this feature!

**Comment by Jaliborc** [comment]
Are you using the release or beta version?

**Comment by Azami1990** [comment]
7.1.0 Beta

**Comment by Jaliborc** [comment]
Should be working now. Let me know if the issue persists @Azami1990
