### ISSUE TITLE
7.2.5 PTR error

### ISSUE THREAD

**Issue by funkydude** [tullamods/Combuctor#94]
`13x ...\common\libs\LibItemSearch-1.2\LibItemSearch-1.2-13.lua:252: attempt to call global 'GetNumEquipmentSets' (a nil value)`

Replaced with `C_EquipmentSet.GetNumEquipmentSets`
Same with:
`GetEquipmentSetInfo` >> `C_EquipmentSet.GetEquipmentSetInfo`
`GetEquipmentSetItemIDs` >> `C_EquipmentSet.GetEquipmentSetIDs`

Note the last one drops the word "Item".

**Comment by Jaliborc** [comment]
Ok, got it

**Comment by funkydude** [comment]
Here is the full list of functions that are deprecated in 7.2.0:
https://www.townlong-yak.com/framexml/ptr/Blizzard_Deprecated/Deprecated_7_2_0.lua
The list for 7.2.5:
https://www.townlong-yak.com/framexml/ptr/Blizzard_Deprecated/Deprecated_7_2_5.lua
